// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file processorClient.cxx
 * Client implementation for interfaces
 *
 * This file was generated by the tool fastddsgen (version: 4.2.1).
 */

#include "processorClient.hpp"

#include <atomic>
#include <exception>
#include <future>
#include <map>
#include <memory>
#include <mutex>
#include <queue>
#include <stdexcept>
#include <string>
#include <thread>

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/domain/qos/RequesterQos.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/rpc/exceptions.hpp>
#include <fastdds/dds/rpc/interfaces.hpp>
#include <fastdds/dds/rpc/RequestInfo.hpp>
#include <fastdds/dds/rpc/Requester.hpp>
#include <fastdds/dds/rpc/Service.hpp>
#include <fastdds/dds/rpc/ServiceTypeSupport.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/rtps/common/Guid.hpp>
#include <fastdds/rtps/common/WriteParams.hpp>

#include "processor.hpp"
#include "processor_details.hpp"
#include "processorPubSubTypes.hpp"

namespace urpc2 {

namespace gen {

//{ interface Processor

namespace detail {

namespace fdds = eprosima::fastdds::dds;
namespace frpc = eprosima::fastdds::dds::rpc;
namespace frtps = eprosima::fastdds::rtps;

class ProcessorClient : public Processor
{

    using RequestType = Processor_Request;
    using ReplyType = Processor_Reply;

public:

    ProcessorClient(
            fdds::DomainParticipant& part,
            const char* service_name,
            const fdds::RequesterQos& qos)
        : Processor()
        , participant_(part)
    {
        // Register the service type support
        auto service_type = create_Processor_service_type_support();
        auto ret = service_type.register_service_type(&participant_, "urpc2::gen::Processor");
        if (ret != fdds::RETCODE_OK)
        {
            throw std::runtime_error("Error registering service type");
        }

        // Create the service
        service_ = participant_.create_service(service_name, "urpc2::gen::Processor");
        if (nullptr == service_)
        {
            throw std::runtime_error("Error creating service");
        }

        // Create the requester
        requester_ = participant_.create_service_requester(service_, qos);
        if (nullptr == requester_)
        {
            throw std::runtime_error("Error creating requester");
        }

        // Start the processing thread
        start_thread();
    }

    ~ProcessorClient() override
    {
        // Stop the processing thread
        stop_thread();

        // Destroy the requester
        if (nullptr != requester_)
        {
            participant_.delete_service_requester(service_->get_service_name(), requester_);
            requester_ = nullptr;
        }

        // Destroy the service
        if (nullptr != service_)
        {
            participant_.delete_service(service_);
            service_ = nullptr;
        }
    }

private:

    void start_thread()
    {
        stop_thread_ = false;
        processing_thread_ = std::thread(&ProcessorClient::run, this);
    }

    void stop_thread()
    {
        stop_thread_ = true;
        if (processing_thread_.joinable())
        {
            processing_thread_.join();
        }
    }

    void run()
    {
        while (!stop_thread_)
        {
            // Wait for a reply
            if (requester_->get_requester_reader()->wait_for_unread_message({ 0, 100000000 }))
            {
                // Take and process the reply
                frpc::RequestInfo req_info;
                ReplyType reply;
                auto ret = requester_->take_reply(&reply, req_info);
                if (ret == fdds::RETCODE_OK)
                {
                    process_reply(reply, req_info);
                }
            }
        }
    }

    void process_reply(
            const ReplyType& reply,
            const frpc::RequestInfo& req_info)
    {
        auto sample_id = req_info.related_sample_identity;
        {
            std::lock_guard<std::mutex> _(mtx_);
            auto it = pending_results_.find(sample_id);
            if (it != pending_results_.end())
            {
                bool should_erase = false;
                it->second->process_reply(reply, req_info, should_erase);
                if (should_erase)
                {
                    pending_results_.erase(it);
                }
            }
        }
    }

    struct IReplyProcessor
    {
        frpc::RequestInfo info;

        virtual ~IReplyProcessor() = default;

        virtual void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) = 0;

    };

    fdds::DomainParticipant& participant_;
    frpc::Service* service_ = nullptr;
    frpc::Requester* requester_ = nullptr;
    std::atomic<bool> stop_thread_{false};
    std::thread processing_thread_;
    std::mutex mtx_;
    std::map<frtps::SampleIdentity, std::shared_ptr<IReplyProcessor>> pending_results_;

    //{ request helpers

    template<typename T, typename TResult>
    std::future<TResult> send_request_with_promise(
            const RequestType& request,
            std::shared_ptr<T> result,
            std::promise<TResult>& promise)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            promise.set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return promise.get_future();
    }

    template<typename T>
    std::shared_ptr<T> send_request_with_reader(
            const RequestType& request,
            std::shared_ptr<T> result)
    {
        result->info.related_sample_identity.writer_guid(requester_->get_requester_reader()->guid());
        if (fdds::RETCODE_OK == requester_->send_request((void*)&request, result->info))
        {
            std::lock_guard<std::mutex> _ (mtx_);
            pending_results_[result->info.related_sample_identity] = result;
        }
        else
        {
            result->set_exception(
                std::make_exception_ptr(frpc::RpcBrokenPipeException(false)));
        }

        return result;
    }

    //} request helpers

    //{ reply helpers

    template<typename T>
    static void set_invalid_reply(
            T& exception_receiver)
    {
        exception_receiver.set_exception(
            std::make_exception_ptr(frpc::RemoteInvalidArgumentError("An invalid reply was received")));
    }

    template<typename T>
    static void set_remote_exception(
            T& exception_receiver,
            const frpc::RemoteExceptionCode_t& exception)
    {
        switch (exception)
        {
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OK:
                set_invalid_reply(exception_receiver);
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNSUPPORTED:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnsupportedError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_INVALID_ARGUMENT:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteInvalidArgumentError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_OUT_OF_RESOURCES:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteOutOfResourcesError()));
                break;
            case frpc::RemoteExceptionCode_t::REMOTE_EX_UNKNOWN_OPERATION:
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownOperationError()));
                break;
            default: // REMOTE_EX_UNKNOWN_EXCEPTION
                exception_receiver.set_exception(std::make_exception_ptr(frpc::RemoteUnknownExceptionError()));
                break;
        }
    }

    static size_t count_reply_fields(
            const ReplyType& reply)
    {
        size_t n_fields = 0;
        n_fields += reply.router.has_value() ? 1 : 0;
        n_fields += reply.remoteEx.has_value() ? 1 : 0;
        return n_fields;
    }

    template<typename T>
    static bool validate_reply(
            std::promise<T>& promise,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(promise);
            return false;
        }

        return true;
    }

    struct IExceptionHolder
    {
        virtual ~IExceptionHolder() = default;

        virtual void set_exception(
                std::exception_ptr exception) = 0;
    };

    static bool validate_reply(
            IExceptionHolder& reader,
            const ReplyType& reply)
    {
        // Check if the reply has one and only one field set
        size_t n_fields = count_reply_fields(reply);
        if (n_fields != 1u)
        {
            set_invalid_reply(reader);
            return false;
        }
        return true;
    }

    //} reply helpers

    //{ operation router

public:

    eprosima::fastdds::dds::rpc::RpcFuture<std::string> router(
            /*in*/ const std::string& handler_name,
            /*in*/ const std::string& args) override
    {
        // Create a promise to hold the result
        auto result = std::make_shared<router_promise>();

        // Create and send the request
        RequestType request;
        request.router = urpc2::gen::detail::Processor_router_In{};
        request.router->handler_name = handler_name;
        request.router->args = args;

        return send_request_with_promise(request, result, result->promise);
    }

private:

    struct router_promise : public IReplyProcessor
    {
        std::promise<std::string> promise;

        void process_reply(
                const ReplyType& reply,
                const frpc::RequestInfo& req_info,
                bool& should_remove) override
        {
            should_remove = false;
            if (req_info.related_sample_identity != info.related_sample_identity)
            {
                return;
            }

            should_remove = true;
            if (!validate_reply(promise, reply))
            {
                return;
            }

            if (reply.remoteEx.has_value())
            {
                set_remote_exception(promise, reply.remoteEx.value());
                return;
            }

            if (reply.router.has_value())
            {
                const auto& result = reply.router.value();
                if (result.result.has_value())
                {
                    const auto& out = result.result.value();
                    promise.set_value(out.return_);
                    return;
                }
            }

            // If we reach this point, the reply is for another operation
            set_invalid_reply(promise);
        }

    };



    //} operation router
 

};

}  // namespace detail

std::shared_ptr<Processor> create_ProcessorClient(
        eprosima::fastdds::dds::DomainParticipant& part,
        const char* service_name,
        const eprosima::fastdds::dds::RequesterQos& qos)
{
    return std::make_shared<detail::ProcessorClient>(part, service_name, qos);
}

//} interface ProcessorClient


} // namespace gen


} // namespace urpc2
