// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file processorTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.2.1).
 */

#include "processorTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include <fastdds/dds/rpc/RPCTypeObjectSupport.hpp>

#include "processor.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace urpc2 {
namespace gen {


namespace detail {

//{ router
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Processor_router_In_type_identifier(
        TypeIdentifierPair& type_ids_Processor_router_In)
{

    ReturnCode_t return_code_Processor_router_In {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Processor_router_In =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "urpc2::gen::detail::Processor_router_In", type_ids_Processor_router_In);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Processor_router_In)
    {
        StructTypeFlag struct_flags_Processor_router_In = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Processor_router_In = "urpc2::gen::detail::Processor_router_In";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Processor_router_In;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Processor_router_In;
        CompleteTypeDetail detail_Processor_router_In = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Processor_router_In, ann_custom_Processor_router_In, type_name_Processor_router_In.to_string());
        CompleteStructHeader header_Processor_router_In;
        header_Processor_router_In = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Processor_router_In);
        CompleteStructMemberSeq member_seq_Processor_router_In;
        {
            TypeIdentifierPair type_ids_handler_name;
            ReturnCode_t return_code_handler_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_handler_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_handler_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_handler_name)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_handler_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_handler_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_handler_name = 0x00000000;
            bool common_handler_name_ec {false};
            CommonStructMember common_handler_name {TypeObjectUtils::build_common_struct_member(member_id_handler_name, member_flags_handler_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_handler_name, common_handler_name_ec))};
            if (!common_handler_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure handler_name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_handler_name = "handler_name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_handler_name;
            ann_custom_Processor_router_In.reset();
            CompleteMemberDetail detail_handler_name = TypeObjectUtils::build_complete_member_detail(name_handler_name, member_ann_builtin_handler_name, ann_custom_Processor_router_In);
            CompleteStructMember member_handler_name = TypeObjectUtils::build_complete_struct_member(common_handler_name, detail_handler_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_Processor_router_In, member_handler_name);
        }
        {
            TypeIdentifierPair type_ids_args;
            ReturnCode_t return_code_args {eprosima::fastdds::dds::RETCODE_OK};
            return_code_args =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_args);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_args)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_args))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_args = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_args = 0x00000001;
            bool common_args_ec {false};
            CommonStructMember common_args {TypeObjectUtils::build_common_struct_member(member_id_args, member_flags_args, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_args, common_args_ec))};
            if (!common_args_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure args member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_args = "args";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_args;
            ann_custom_Processor_router_In.reset();
            CompleteMemberDetail detail_args = TypeObjectUtils::build_complete_member_detail(name_args, member_ann_builtin_args, ann_custom_Processor_router_In);
            CompleteStructMember member_args = TypeObjectUtils::build_complete_struct_member(common_args, detail_args);
            TypeObjectUtils::add_complete_struct_member(member_seq_Processor_router_In, member_args);
        }
        CompleteStructType struct_type_Processor_router_In = TypeObjectUtils::build_complete_struct_type(struct_flags_Processor_router_In, header_Processor_router_In, member_seq_Processor_router_In);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Processor_router_In, type_name_Processor_router_In.to_string(), type_ids_Processor_router_In))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "urpc2::gen::detail::Processor_router_In already registered in TypeObjectRegistry for a different type.");
        }
    }
}

  

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Processor_router_Out_type_identifier(
        TypeIdentifierPair& type_ids_Processor_router_Out)
{

    ReturnCode_t return_code_Processor_router_Out {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Processor_router_Out =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "urpc2::gen::detail::Processor_router_Out", type_ids_Processor_router_Out);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Processor_router_Out)
    {
        StructTypeFlag struct_flags_Processor_router_Out = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_Processor_router_Out = "urpc2::gen::detail::Processor_router_Out";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Processor_router_Out;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Processor_router_Out;
        CompleteTypeDetail detail_Processor_router_Out = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Processor_router_Out, ann_custom_Processor_router_Out, type_name_Processor_router_Out.to_string());
        CompleteStructHeader header_Processor_router_Out;
        header_Processor_router_Out = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Processor_router_Out);
        CompleteStructMemberSeq member_seq_Processor_router_Out;
        {
            TypeIdentifierPair type_ids_return_;
            ReturnCode_t return_code_return_ {eprosima::fastdds::dds::RETCODE_OK};
            return_code_return_ =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_return_);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_return_)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_return_))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_return_ = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_return_ = 0x00000000;
            bool common_return__ec {false};
            CommonStructMember common_return_ {TypeObjectUtils::build_common_struct_member(member_id_return_, member_flags_return_, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_return_, common_return__ec))};
            if (!common_return__ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure return_ member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_return_ = "return_";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_return_;
            ann_custom_Processor_router_Out.reset();
            CompleteMemberDetail detail_return_ = TypeObjectUtils::build_complete_member_detail(name_return_, member_ann_builtin_return_, ann_custom_Processor_router_Out);
            CompleteStructMember member_return_ = TypeObjectUtils::build_complete_struct_member(common_return_, detail_return_);
            TypeObjectUtils::add_complete_struct_member(member_seq_Processor_router_Out, member_return_);
        }
        CompleteStructType struct_type_Processor_router_Out = TypeObjectUtils::build_complete_struct_type(struct_flags_Processor_router_Out, header_Processor_router_Out, member_seq_Processor_router_Out);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Processor_router_Out, type_name_Processor_router_Out.to_string(), type_ids_Processor_router_Out))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "urpc2::gen::detail::Processor_router_Out already registered in TypeObjectRegistry for a different type.");
        }
    }
}

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Processor_router_Result_type_identifier(
        TypeIdentifierPair& type_ids_Processor_router_Result)
{

    ReturnCode_t return_code_Processor_router_Result {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Processor_router_Result =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "urpc2::gen::detail::Processor_router_Result", type_ids_Processor_router_Result);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Processor_router_Result)
    {
        StructTypeFlag struct_flags_Processor_router_Result = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::MUTABLE,
                false, false);
        QualifiedTypeName type_name_Processor_router_Result = "urpc2::gen::detail::Processor_router_Result";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Processor_router_Result;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Processor_router_Result;
        CompleteTypeDetail detail_Processor_router_Result = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Processor_router_Result, ann_custom_Processor_router_Result, type_name_Processor_router_Result.to_string());
        CompleteStructHeader header_Processor_router_Result;
        header_Processor_router_Result = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Processor_router_Result);
        CompleteStructMemberSeq member_seq_Processor_router_Result;
        {
            TypeIdentifierPair type_ids_result;
            ReturnCode_t return_code_result {eprosima::fastdds::dds::RETCODE_OK};
            return_code_result =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "urpc2::gen::detail::Processor_router_Out", type_ids_result);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_result)
            {
                ::urpc2::gen::detail::register_Processor_router_Out_type_identifier(type_ids_result);
            }
            StructMemberFlag member_flags_result = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    true, false, false, false);
            MemberId member_id_result = 0x0784a8b4;
            bool common_result_ec {false};
            CommonStructMember common_result {TypeObjectUtils::build_common_struct_member(member_id_result, member_flags_result, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_result, common_result_ec))};
            if (!common_result_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure result member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_result = "result";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_result;
            ann_custom_Processor_router_Result.reset();
            AppliedAnnotationSeq tmp_ann_custom_result;
            eprosima::fastcdr::optional<std::string> unit_result;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_result;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_result;
            eprosima::fastcdr::optional<std::string> hash_id_result;
            hash_id_result = "";

            if (unit_result.has_value() || min_result.has_value() || max_result.has_value() || hash_id_result.has_value())
            {
                member_ann_builtin_result = TypeObjectUtils::build_applied_builtin_member_annotations(unit_result, min_result, max_result, hash_id_result);
            }
            if (!tmp_ann_custom_result.empty())
            {
                ann_custom_Processor_router_Result = tmp_ann_custom_result;
            }
            CompleteMemberDetail detail_result = TypeObjectUtils::build_complete_member_detail(name_result, member_ann_builtin_result, ann_custom_Processor_router_Result);
            CompleteStructMember member_result = TypeObjectUtils::build_complete_struct_member(common_result, detail_result);
            TypeObjectUtils::add_complete_struct_member(member_seq_Processor_router_Result, member_result);
        }
        CompleteStructType struct_type_Processor_router_Result = TypeObjectUtils::build_complete_struct_type(struct_flags_Processor_router_Result, header_Processor_router_Result, member_seq_Processor_router_Result);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Processor_router_Result, type_name_Processor_router_Result.to_string(), type_ids_Processor_router_Result))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "urpc2::gen::detail::Processor_router_Result already registered in TypeObjectRegistry for a different type.");
        }
    }
}

//}  // router
 

}  // namespace detail

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Processor_Request_type_identifier(
        TypeIdentifierPair& type_ids_Processor_Request)
{

    ReturnCode_t return_code_Processor_Request {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Processor_Request =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "urpc2::gen::detail::Processor_Request", type_ids_Processor_Request);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Processor_Request)
    {
        StructTypeFlag struct_flags_Processor_Request = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::MUTABLE,
                false, false);
        QualifiedTypeName type_name_Processor_Request = "urpc2::gen::detail::Processor_Request";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Processor_Request;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Processor_Request;
        CompleteTypeDetail detail_Processor_Request = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Processor_Request, ann_custom_Processor_Request, type_name_Processor_Request.to_string());
        CompleteStructHeader header_Processor_Request;
        header_Processor_Request = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Processor_Request);
        CompleteStructMemberSeq member_seq_Processor_Request;
        {
            TypeIdentifierPair type_ids_router;
            ReturnCode_t return_code_router {eprosima::fastdds::dds::RETCODE_OK};
            return_code_router =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "urpc2::gen::detail::Processor_router_In", type_ids_router);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_router)
            {
                ::urpc2::gen::detail::register_Processor_router_In_type_identifier(type_ids_router);
            }
            StructMemberFlag member_flags_router = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    true, false, false, false);
            MemberId member_id_router = 0x055c39f3;
            bool common_router_ec {false};
            CommonStructMember common_router {TypeObjectUtils::build_common_struct_member(member_id_router, member_flags_router, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_router, common_router_ec))};
            if (!common_router_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure router member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_router = "router";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_router;
            ann_custom_Processor_Request.reset();
            AppliedAnnotationSeq tmp_ann_custom_router;
            eprosima::fastcdr::optional<std::string> unit_router;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_router;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_router;
            eprosima::fastcdr::optional<std::string> hash_id_router;
            hash_id_router = "";

            if (unit_router.has_value() || min_router.has_value() || max_router.has_value() || hash_id_router.has_value())
            {
                member_ann_builtin_router = TypeObjectUtils::build_applied_builtin_member_annotations(unit_router, min_router, max_router, hash_id_router);
            }
            if (!tmp_ann_custom_router.empty())
            {
                ann_custom_Processor_Request = tmp_ann_custom_router;
            }
            CompleteMemberDetail detail_router = TypeObjectUtils::build_complete_member_detail(name_router, member_ann_builtin_router, ann_custom_Processor_Request);
            CompleteStructMember member_router = TypeObjectUtils::build_complete_struct_member(common_router, detail_router);
            TypeObjectUtils::add_complete_struct_member(member_seq_Processor_Request, member_router);
        }
        CompleteStructType struct_type_Processor_Request = TypeObjectUtils::build_complete_struct_type(struct_flags_Processor_Request, header_Processor_Request, member_seq_Processor_Request);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Processor_Request, type_name_Processor_Request.to_string(), type_ids_Processor_Request))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "urpc2::gen::detail::Processor_Request already registered in TypeObjectRegistry for a different type.");
        }
    }
}
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Processor_Reply_type_identifier(
        TypeIdentifierPair& type_ids_Processor_Reply)
{

    ReturnCode_t return_code_Processor_Reply {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Processor_Reply =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "urpc2::gen::detail::Processor_Reply", type_ids_Processor_Reply);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Processor_Reply)
    {
        StructTypeFlag struct_flags_Processor_Reply = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::MUTABLE,
                false, false);
        QualifiedTypeName type_name_Processor_Reply = "urpc2::gen::detail::Processor_Reply";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Processor_Reply;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Processor_Reply;
        CompleteTypeDetail detail_Processor_Reply = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Processor_Reply, ann_custom_Processor_Reply, type_name_Processor_Reply.to_string());
        CompleteStructHeader header_Processor_Reply;
        header_Processor_Reply = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Processor_Reply);
        CompleteStructMemberSeq member_seq_Processor_Reply;
        {
            TypeIdentifierPair type_ids_router;
            ReturnCode_t return_code_router {eprosima::fastdds::dds::RETCODE_OK};
            return_code_router =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "urpc2::gen::detail::Processor_router_Result", type_ids_router);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_router)
            {
                ::urpc2::gen::detail::register_Processor_router_Result_type_identifier(type_ids_router);
            }
            StructMemberFlag member_flags_router = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    true, false, false, false);
            MemberId member_id_router = 0x055c39f3;
            bool common_router_ec {false};
            CommonStructMember common_router {TypeObjectUtils::build_common_struct_member(member_id_router, member_flags_router, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_router, common_router_ec))};
            if (!common_router_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure router member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_router = "router";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_router;
            ann_custom_Processor_Reply.reset();
            AppliedAnnotationSeq tmp_ann_custom_router;
            eprosima::fastcdr::optional<std::string> unit_router;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_router;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_router;
            eprosima::fastcdr::optional<std::string> hash_id_router;
            hash_id_router = "";

            if (unit_router.has_value() || min_router.has_value() || max_router.has_value() || hash_id_router.has_value())
            {
                member_ann_builtin_router = TypeObjectUtils::build_applied_builtin_member_annotations(unit_router, min_router, max_router, hash_id_router);
            }
            if (!tmp_ann_custom_router.empty())
            {
                ann_custom_Processor_Reply = tmp_ann_custom_router;
            }
            CompleteMemberDetail detail_router = TypeObjectUtils::build_complete_member_detail(name_router, member_ann_builtin_router, ann_custom_Processor_Reply);
            CompleteStructMember member_router = TypeObjectUtils::build_complete_struct_member(common_router, detail_router);
            TypeObjectUtils::add_complete_struct_member(member_seq_Processor_Reply, member_router);
        }
        {
            TypeIdentifierPair type_ids_remoteEx;
            ReturnCode_t return_code_remoteEx {eprosima::fastdds::dds::RETCODE_OK};
            return_code_remoteEx =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "eprosima::fastdds::dds::rpc::RemoteExceptionCode_t", type_ids_remoteEx);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_remoteEx)
            {
                ::eprosima::fastdds::dds::rpc::register_RemoteExceptionCode_t_type_identifier(type_ids_remoteEx);
            }
            StructMemberFlag member_flags_remoteEx = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    true, false, false, false);
            MemberId member_id_remoteEx = 0x0f8e48f0;
            bool common_remoteEx_ec {false};
            CommonStructMember common_remoteEx {TypeObjectUtils::build_common_struct_member(member_id_remoteEx, member_flags_remoteEx, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_remoteEx, common_remoteEx_ec))};
            if (!common_remoteEx_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure remoteEx member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_remoteEx = "remoteEx";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_remoteEx;
            ann_custom_Processor_Reply.reset();
            AppliedAnnotationSeq tmp_ann_custom_remoteEx;
            eprosima::fastcdr::optional<std::string> unit_remoteEx;
            eprosima::fastcdr::optional<AnnotationParameterValue> min_remoteEx;
            eprosima::fastcdr::optional<AnnotationParameterValue> max_remoteEx;
            eprosima::fastcdr::optional<std::string> hash_id_remoteEx;
            hash_id_remoteEx = "";

            if (unit_remoteEx.has_value() || min_remoteEx.has_value() || max_remoteEx.has_value() || hash_id_remoteEx.has_value())
            {
                member_ann_builtin_remoteEx = TypeObjectUtils::build_applied_builtin_member_annotations(unit_remoteEx, min_remoteEx, max_remoteEx, hash_id_remoteEx);
            }
            if (!tmp_ann_custom_remoteEx.empty())
            {
                ann_custom_Processor_Reply = tmp_ann_custom_remoteEx;
            }
            CompleteMemberDetail detail_remoteEx = TypeObjectUtils::build_complete_member_detail(name_remoteEx, member_ann_builtin_remoteEx, ann_custom_Processor_Reply);
            CompleteStructMember member_remoteEx = TypeObjectUtils::build_complete_struct_member(common_remoteEx, detail_remoteEx);
            TypeObjectUtils::add_complete_struct_member(member_seq_Processor_Reply, member_remoteEx);
        }
        CompleteStructType struct_type_Processor_Reply = TypeObjectUtils::build_complete_struct_type(struct_flags_Processor_Reply, header_Processor_Reply, member_seq_Processor_Reply);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Processor_Reply, type_name_Processor_Reply.to_string(), type_ids_Processor_Reply))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "urpc2::gen::detail::Processor_Reply already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace gen

} // namespace urpc2

