// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file processorServerImpl.hpp
 * Server implementation for interfaces
 *
 * This file was generated by the tool fastddsgen (version: 4.2.1).
 */

#ifndef FAST_DDS_GENERATED__PROCESSOR_SERVERIMPL_HPP
#define FAST_DDS_GENERATED__PROCESSOR_SERVERIMPL_HPP

#include "processor.hpp"
#include "processorServer.hpp"

namespace urpc2 {

namespace gen {

//{ interface Processor

struct ProcessorServerImplementation :
    public ProcessorServer_IServerImplementation
{

    urpc2::gen::OctetSeq router(
            const eprosima::fastdds::dds::rpc::RpcRequest& info,
            /*in*/ const std::string& handler_name,
            /*in*/ const urpc2::gen::OctetSeq& args) override
    {
        static_cast<void>(info);
        static_cast<void>(handler_name);
        static_cast<void>(args);
        throw eprosima::fastdds::dds::rpc::RemoteUnsupportedError("Operation 'router' is not implemented");
    }

};

//} interface Processor


} // namespace gen


} // namespace urpc2


#endif  // FAST_DDS_GENERATED__PROCESSOR_SERVERIMPL_HPP
