// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file processor.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.1).
 */

#ifndef FAST_DDS_GENERATED__PROCESSOR_HPP
#define FAST_DDS_GENERATED__PROCESSOR_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/rpc/interfaces/RpcFuture.hpp>


#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(PROCESSOR_SOURCE)
#define PROCESSOR_DllAPI __declspec( dllexport )
#else
#define PROCESSOR_DllAPI __declspec( dllimport )
#endif // PROCESSOR_SOURCE
#else
#define PROCESSOR_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define PROCESSOR_DllAPI
#endif // _WIN32

namespace urpc2 {

namespace gen {


/*!
 * @brief This class represents the interface Processor defined by the user in the IDL file.
 * @ingroup processor
 */
class eProsima_user_DllExport Processor 
{
public:
    virtual ~Processor() = default;


    virtual eprosima::fastdds::dds::rpc::RpcFuture<std::string> router(
            /*in*/ const std::string& handler_name,
            /*in*/ const std::string& args) = 0;

};



} // namespace gen

} // namespace urpc2

#endif // _FAST_DDS_GENERATED_PROCESSOR_HPP_


