module calculator_example {
    exception OverflowException {};  // 当运算结果无法用 32 位整数表示时抛出
    interface Calculator {
        void representation_limits(out long min_value, out long max_value);
        long addition(in long value1, in long value2) raises (OverflowException);
    };
};
