// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file processor_details.hpp
 * This header file contains support data structures for RPC communication.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.1).
 */

#ifndef FAST_DDS_GENERATED__PROCESSOR_DETAILS_HPP
#define FAST_DDS_GENERATED__PROCESSOR_DETAILS_HPP

#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/rpc/RemoteExceptionCode_t.hpp>
#include <fastdds/dds/rpc/interfaces/RpcStatusCode.hpp>

#include "processor.hpp"

namespace urpc2 {
namespace detail {

//{ Processor interface

//{ router
struct Processor_router_In
{
    std::string handler_name; 
    std::string args; 
};

  

struct Processor_router_Out
{
    std::string return_;
};

struct Processor_router_Result
{
    eprosima::fastcdr::optional<urpc2::detail::Processor_router_Out> result;
};

//}  // router
 

//{ top level

struct Processor_Request
{
    eprosima::fastcdr::optional<urpc2::detail::Processor_router_In> router;   
};

struct Processor_Reply
{
    eprosima::fastcdr::optional<urpc2::detail::Processor_router_Result> router; 
    eprosima::fastcdr::optional<eprosima::fastdds::dds::rpc::RemoteExceptionCode_t> remoteEx;
};

//}  // top level

//}  // Processor interface

} // namespace detail
}  // namespace urpc2

#endif //FAST_DDS_GENERATED__PROCESSOR_DETAILS_HPP